### ISSUE TITLE
Readme clarification

### ISSUE THREAD

**Issue by wtmoose** [bennibrightside/ShadowView#1]
This is a handy component, but the following statement doesn't seem accurate:

> > Normally it's not possible to set a corner radius and a shadow on a UIView subclass. This is because the property clipsToBounds must be set to true for the view to render the rounded corners, which also clips the shadow away.

The following `UIView` subclass will happily display a corner radius and a drop shadow. Consider clarifying the readme.

```
class ShadowView: UIView {

    override func awakeFromNib() {
        super.awakeFromNib()
        layer.masksToBounds = false
        layer.cornerRadius = 10.0
        layer.shadowColor = UIColor.blackColor().CGColor
        layer.shadowOffset = CGSize(width: 0.0, height: 2.0)
        layer.shadowRadius = 6.0
        layer.shadowOpacity = 0.4
        updateShadowPath()
    }

    private func updateShadowPath() {
        layer.shadowPath = UIBezierPath(roundedRect: layer.bounds, cornerRadius: layer.cornerRadius).CGPath
    }

    override func layoutSubviews() {
        super.layoutSubviews()
        updateShadowPath()
    }
}
```

**Comment by benboecker** [comment]
Thanks for the feedback, this really is a much simpler solution. I will use this implementation for the next update and mention you accordingly!
